# Generated by Django 3.0.2 on 2020-01-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='umowa',
        ),
        migrations.AddField(
            model_name='umowa',
            name='pracownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schronisko.Pracownik'),
        ),
    ]
