# Generated by Django 3.0.2 on 2020-01-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0002_auto_20200130_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umowa',
            name='pracownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schronisko.Pracownik'),
        ),
    ]
