# Generated by Django 3.0.2 on 2020-01-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schronisko', '0003_auto_20200130_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='boks',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zwierze',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='zwierzeta', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
