# Generated by Django 3.0.2 on 2020-01-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0005_auto_20200130_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boks',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='zwierze',
            name='owner',
        ),
    ]
