# Generated by Django 3.0.2 on 2020-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0012_auto_20200130_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='autor',
        ),
    ]
